#include "config.h"
#include "cmdline.h" // Generated by gengetopt
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// The required length of a 2FA code.
#define TWO_FA_CODE_LENGTH 6

app_config_t *config_create(int argc, char *argv[]) {
    struct gengetopt_args_info args_info;
    app_config_t *config = NULL;

    // Allocate memory for the configuration struct.
    config = calloc(1, sizeof(app_config_t));
    if (config == NULL) {
        perror("Failed to allocate memory for config");
        return NULL;
    }

    // Parse the command line arguments using the generated parser.
    if (cmdline_parser(argc, argv, &args_info) != 0) {
        fprintf(stderr, "Failed to parse command line arguments.\n");
        goto cleanup_error;
    }

    // --- Transfer parsed arguments to the config struct ---
    config->decrypt_port = args_info.decrypt_port_arg;
    config->m3u8_port = args_info.m3u8_port_arg;
    config->login_given = args_info.login_given;
    config->code_from_file = args_info.code_from_file_flag;

    config->host = strdup(args_info.host_arg);
    if (config->host == NULL) {
        perror("Failed to duplicate host string");
        goto cleanup_error;
    }

    if (args_info.proxy_given) {
        config->proxy = strdup(args_info.proxy_arg);
        if (config->proxy == NULL) {
            perror("Failed to duplicate proxy string");
            goto cleanup_error;
        }
    }

    if (config->login_given) {
        char *login_str = args_info.login_arg;
        char *username_token = strtok(login_str, ":");
        char *pass_token = strtok(NULL, "");

        if (username_token == NULL || pass_token == NULL) {
            fprintf(stderr, "Invalid login format. Expected 'username:password'.\n");
            goto cleanup_error;
        }

        config->username = strdup(username_token);
        if (config->username == NULL) {
            perror("Failed to duplicate username string");
            goto cleanup_error;
        }

        size_t pass_len = strlen(pass_token);
        size_t buffer_size = pass_len + TWO_FA_CODE_LENGTH + 1;
        config->password = malloc(buffer_size);
        if (config->password == NULL) {
            perror("Failed to allocate memory for password");
            goto cleanup_error;
        }
        strcpy(config->password, pass_token);
    }

    cmdline_parser_free(&args_info);
    return config;

cleanup_error:
    cmdline_parser_free(&args_info);
    config_destroy(config);
    return NULL;
}

void config_destroy(app_config_t *config) {
    if (config == NULL) {
        return;
    }
    free((void *)config->host);
    free((void *)config->proxy);
    free(config->username);
    free(config->password);
    free(config);
}
